const locations = [
  {
    id: 1,
    name: 'Earth (C-137)',
    type: 'Planet',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/38',
      'https://rickandmortyapi.com/api/character/45',
      'https://rickandmortyapi.com/api/character/71',
      'https://rickandmortyapi.com/api/character/82',
      'https://rickandmortyapi.com/api/character/83',
      'https://rickandmortyapi.com/api/character/92',
      'https://rickandmortyapi.com/api/character/112',
      'https://rickandmortyapi.com/api/character/114',
      'https://rickandmortyapi.com/api/character/116',
      'https://rickandmortyapi.com/api/character/117',
      'https://rickandmortyapi.com/api/character/120',
      'https://rickandmortyapi.com/api/character/127',
      'https://rickandmortyapi.com/api/character/155',
      'https://rickandmortyapi.com/api/character/169',
      'https://rickandmortyapi.com/api/character/175',
      'https://rickandmortyapi.com/api/character/179',
      'https://rickandmortyapi.com/api/character/186',
      'https://rickandmortyapi.com/api/character/201',
      'https://rickandmortyapi.com/api/character/216',
      'https://rickandmortyapi.com/api/character/239',
      'https://rickandmortyapi.com/api/character/271',
      'https://rickandmortyapi.com/api/character/302',
      'https://rickandmortyapi.com/api/character/303',
      'https://rickandmortyapi.com/api/character/338',
      'https://rickandmortyapi.com/api/character/343',
      'https://rickandmortyapi.com/api/character/356',
      'https://rickandmortyapi.com/api/character/394',
    ],
    url: 'https://rickandmortyapi.com/api/location/1',
    created: '2017-11-10T12:42:04.162Z',
  },
  {
    id: 2,
    name: 'Abadango',
    type: 'Cluster',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/6'],
    url: 'https://rickandmortyapi.com/api/location/2',
    created: '2017-11-10T13:06:38.182Z',
  },
  {
    id: 3,
    name: 'Citadel of Ricks',
    type: 'Space station',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/8',
      'https://rickandmortyapi.com/api/character/14',
      'https://rickandmortyapi.com/api/character/15',
      'https://rickandmortyapi.com/api/character/18',
      'https://rickandmortyapi.com/api/character/21',
      'https://rickandmortyapi.com/api/character/22',
      'https://rickandmortyapi.com/api/character/27',
      'https://rickandmortyapi.com/api/character/42',
      'https://rickandmortyapi.com/api/character/43',
      'https://rickandmortyapi.com/api/character/44',
      'https://rickandmortyapi.com/api/character/48',
      'https://rickandmortyapi.com/api/character/53',
      'https://rickandmortyapi.com/api/character/56',
      'https://rickandmortyapi.com/api/character/61',
      'https://rickandmortyapi.com/api/character/69',
      'https://rickandmortyapi.com/api/character/72',
      'https://rickandmortyapi.com/api/character/73',
      'https://rickandmortyapi.com/api/character/74',
      'https://rickandmortyapi.com/api/character/77',
      'https://rickandmortyapi.com/api/character/78',
      'https://rickandmortyapi.com/api/character/85',
      'https://rickandmortyapi.com/api/character/86',
      'https://rickandmortyapi.com/api/character/95',
      'https://rickandmortyapi.com/api/character/118',
      'https://rickandmortyapi.com/api/character/119',
      'https://rickandmortyapi.com/api/character/123',
      'https://rickandmortyapi.com/api/character/135',
      'https://rickandmortyapi.com/api/character/143',
      'https://rickandmortyapi.com/api/character/152',
      'https://rickandmortyapi.com/api/character/164',
      'https://rickandmortyapi.com/api/character/165',
      'https://rickandmortyapi.com/api/character/187',
      'https://rickandmortyapi.com/api/character/200',
      'https://rickandmortyapi.com/api/character/206',
      'https://rickandmortyapi.com/api/character/209',
      'https://rickandmortyapi.com/api/character/220',
      'https://rickandmortyapi.com/api/character/229',
      'https://rickandmortyapi.com/api/character/231',
      'https://rickandmortyapi.com/api/character/235',
      'https://rickandmortyapi.com/api/character/267',
      'https://rickandmortyapi.com/api/character/278',
      'https://rickandmortyapi.com/api/character/281',
      'https://rickandmortyapi.com/api/character/283',
      'https://rickandmortyapi.com/api/character/284',
      'https://rickandmortyapi.com/api/character/285',
      'https://rickandmortyapi.com/api/character/286',
      'https://rickandmortyapi.com/api/character/287',
      'https://rickandmortyapi.com/api/character/288',
      'https://rickandmortyapi.com/api/character/289',
      'https://rickandmortyapi.com/api/character/291',
      'https://rickandmortyapi.com/api/character/295',
      'https://rickandmortyapi.com/api/character/298',
      'https://rickandmortyapi.com/api/character/299',
      'https://rickandmortyapi.com/api/character/322',
      'https://rickandmortyapi.com/api/character/325',
      'https://rickandmortyapi.com/api/character/328',
      'https://rickandmortyapi.com/api/character/330',
      'https://rickandmortyapi.com/api/character/345',
      'https://rickandmortyapi.com/api/character/359',
      'https://rickandmortyapi.com/api/character/366',
      'https://rickandmortyapi.com/api/character/378',
      'https://rickandmortyapi.com/api/character/385',
      'https://rickandmortyapi.com/api/character/392',
      'https://rickandmortyapi.com/api/character/461',
      'https://rickandmortyapi.com/api/character/462',
      'https://rickandmortyapi.com/api/character/463',
      'https://rickandmortyapi.com/api/character/464',
      'https://rickandmortyapi.com/api/character/465',
      'https://rickandmortyapi.com/api/character/466',
      'https://rickandmortyapi.com/api/character/472',
      'https://rickandmortyapi.com/api/character/473',
      'https://rickandmortyapi.com/api/character/474',
      'https://rickandmortyapi.com/api/character/475',
      'https://rickandmortyapi.com/api/character/476',
      'https://rickandmortyapi.com/api/character/477',
      'https://rickandmortyapi.com/api/character/478',
      'https://rickandmortyapi.com/api/character/479',
      'https://rickandmortyapi.com/api/character/480',
      'https://rickandmortyapi.com/api/character/481',
      'https://rickandmortyapi.com/api/character/482',
      'https://rickandmortyapi.com/api/character/483',
      'https://rickandmortyapi.com/api/character/484',
      'https://rickandmortyapi.com/api/character/485',
      'https://rickandmortyapi.com/api/character/486',
      'https://rickandmortyapi.com/api/character/487',
      'https://rickandmortyapi.com/api/character/488',
      'https://rickandmortyapi.com/api/character/489',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/801',
      'https://rickandmortyapi.com/api/character/802',
      'https://rickandmortyapi.com/api/character/803',
      'https://rickandmortyapi.com/api/character/804',
      'https://rickandmortyapi.com/api/character/805',
      'https://rickandmortyapi.com/api/character/806',
      'https://rickandmortyapi.com/api/character/810',
      'https://rickandmortyapi.com/api/character/811',
      'https://rickandmortyapi.com/api/character/812',
      'https://rickandmortyapi.com/api/character/819',
      'https://rickandmortyapi.com/api/character/820',
      'https://rickandmortyapi.com/api/character/818',
    ],
    url: 'https://rickandmortyapi.com/api/location/3',
    created: '2017-11-10T13:08:13.191Z',
  },
  {
    id: 4,
    name: "Worldender's lair",
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/10',
      'https://rickandmortyapi.com/api/character/81',
      'https://rickandmortyapi.com/api/character/208',
      'https://rickandmortyapi.com/api/character/226',
      'https://rickandmortyapi.com/api/character/340',
      'https://rickandmortyapi.com/api/character/362',
      'https://rickandmortyapi.com/api/character/375',
      'https://rickandmortyapi.com/api/character/382',
      'https://rickandmortyapi.com/api/character/395',
    ],
    url: 'https://rickandmortyapi.com/api/location/4',
    created: '2017-11-10T13:08:20.569Z',
  },
  {
    id: 5,
    name: 'Anatomy Park',
    type: 'Microverse',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/12',
      'https://rickandmortyapi.com/api/character/17',
      'https://rickandmortyapi.com/api/character/96',
      'https://rickandmortyapi.com/api/character/97',
      'https://rickandmortyapi.com/api/character/98',
      'https://rickandmortyapi.com/api/character/99',
      'https://rickandmortyapi.com/api/character/100',
      'https://rickandmortyapi.com/api/character/101',
      'https://rickandmortyapi.com/api/character/108',
      'https://rickandmortyapi.com/api/character/268',
      'https://rickandmortyapi.com/api/character/300',
    ],
    url: 'https://rickandmortyapi.com/api/location/5',
    created: '2017-11-10T13:08:46.060Z',
  },
  {
    id: 6,
    name: 'Interdimensional Cable',
    type: 'TV',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/20',
      'https://rickandmortyapi.com/api/character/28',
      'https://rickandmortyapi.com/api/character/29',
      'https://rickandmortyapi.com/api/character/34',
      'https://rickandmortyapi.com/api/character/49',
      'https://rickandmortyapi.com/api/character/51',
      'https://rickandmortyapi.com/api/character/54',
      'https://rickandmortyapi.com/api/character/121',
      'https://rickandmortyapi.com/api/character/126',
      'https://rickandmortyapi.com/api/character/129',
      'https://rickandmortyapi.com/api/character/134',
      'https://rickandmortyapi.com/api/character/136',
      'https://rickandmortyapi.com/api/character/145',
      'https://rickandmortyapi.com/api/character/157',
      'https://rickandmortyapi.com/api/character/173',
      'https://rickandmortyapi.com/api/character/184',
      'https://rickandmortyapi.com/api/character/205',
      'https://rickandmortyapi.com/api/character/207',
      'https://rickandmortyapi.com/api/character/214',
      'https://rickandmortyapi.com/api/character/222',
      'https://rickandmortyapi.com/api/character/223',
      'https://rickandmortyapi.com/api/character/224',
      'https://rickandmortyapi.com/api/character/225',
      'https://rickandmortyapi.com/api/character/250',
      'https://rickandmortyapi.com/api/character/254',
      'https://rickandmortyapi.com/api/character/260',
      'https://rickandmortyapi.com/api/character/264',
      'https://rickandmortyapi.com/api/character/266',
      'https://rickandmortyapi.com/api/character/275',
      'https://rickandmortyapi.com/api/character/277',
      'https://rickandmortyapi.com/api/character/279',
      'https://rickandmortyapi.com/api/character/312',
      'https://rickandmortyapi.com/api/character/314',
      'https://rickandmortyapi.com/api/character/315',
      'https://rickandmortyapi.com/api/character/316',
      'https://rickandmortyapi.com/api/character/317',
      'https://rickandmortyapi.com/api/character/318',
      'https://rickandmortyapi.com/api/character/334',
      'https://rickandmortyapi.com/api/character/351',
      'https://rickandmortyapi.com/api/character/358',
      'https://rickandmortyapi.com/api/character/367',
      'https://rickandmortyapi.com/api/character/370',
      'https://rickandmortyapi.com/api/character/373',
      'https://rickandmortyapi.com/api/character/403',
      'https://rickandmortyapi.com/api/character/406',
      'https://rickandmortyapi.com/api/character/407',
      'https://rickandmortyapi.com/api/character/408',
      'https://rickandmortyapi.com/api/character/409',
      'https://rickandmortyapi.com/api/character/410',
      'https://rickandmortyapi.com/api/character/411',
      'https://rickandmortyapi.com/api/character/412',
      'https://rickandmortyapi.com/api/character/413',
      'https://rickandmortyapi.com/api/character/414',
      'https://rickandmortyapi.com/api/character/415',
      'https://rickandmortyapi.com/api/character/416',
      'https://rickandmortyapi.com/api/character/417',
      'https://rickandmortyapi.com/api/character/418',
      'https://rickandmortyapi.com/api/character/457',
      'https://rickandmortyapi.com/api/character/458',
      'https://rickandmortyapi.com/api/character/459',
      'https://rickandmortyapi.com/api/character/709',
      'https://rickandmortyapi.com/api/character/711',
    ],
    url: 'https://rickandmortyapi.com/api/location/6',
    created: '2017-11-10T13:09:09.102Z',
  },
  {
    id: 7,
    name: 'Immortality Field Resort',
    type: 'Resort',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/23',
      'https://rickandmortyapi.com/api/character/204',
      'https://rickandmortyapi.com/api/character/320',
    ],
    url: 'https://rickandmortyapi.com/api/location/7',
    created: '2017-11-10T13:09:17.136Z',
  },
  {
    id: 8,
    name: 'Post-Apocalyptic Earth',
    type: 'Planet',
    dimension: 'Post-Apocalyptic Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/25',
      'https://rickandmortyapi.com/api/character/52',
      'https://rickandmortyapi.com/api/character/68',
      'https://rickandmortyapi.com/api/character/110',
      'https://rickandmortyapi.com/api/character/111',
      'https://rickandmortyapi.com/api/character/140',
      'https://rickandmortyapi.com/api/character/156',
      'https://rickandmortyapi.com/api/character/228',
      'https://rickandmortyapi.com/api/character/323',
      'https://rickandmortyapi.com/api/character/342',
    ],
    url: 'https://rickandmortyapi.com/api/location/8',
    created: '2017-11-10T13:09:22.551Z',
  },
  {
    id: 9,
    name: 'Purge Planet',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/26',
      'https://rickandmortyapi.com/api/character/139',
      'https://rickandmortyapi.com/api/character/202',
      'https://rickandmortyapi.com/api/character/273',
    ],
    url: 'https://rickandmortyapi.com/api/location/9',
    created: '2017-11-10T13:09:29.566Z',
  },
  {
    id: 10,
    name: 'Venzenulon 7',
    type: 'Planet',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/33'],
    url: 'https://rickandmortyapi.com/api/location/10',
    created: '2017-11-18T11:21:51.643Z',
  },
  {
    id: 11,
    name: 'Bepis 9',
    type: 'Planet',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/35'],
    url: 'https://rickandmortyapi.com/api/location/11',
    created: '2017-11-18T11:26:03.325Z',
  },
  {
    id: 12,
    name: 'Cronenberg Earth',
    type: 'Planet',
    dimension: 'Cronenberg Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/12',
    created: '2017-11-18T11:29:27.857Z',
  },
  {
    id: 13,
    name: 'Nuptia 4',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/40',
      'https://rickandmortyapi.com/api/character/55',
      'https://rickandmortyapi.com/api/character/131',
      'https://rickandmortyapi.com/api/character/132',
      'https://rickandmortyapi.com/api/character/146',
      'https://rickandmortyapi.com/api/character/148',
      'https://rickandmortyapi.com/api/character/163',
      'https://rickandmortyapi.com/api/character/178',
      'https://rickandmortyapi.com/api/character/310',
      'https://rickandmortyapi.com/api/character/386',
      'https://rickandmortyapi.com/api/character/387',
    ],
    url: 'https://rickandmortyapi.com/api/location/13',
    created: '2017-11-18T11:30:29.780Z',
  },
  {
    id: 14,
    name: "Giant's Town",
    type: 'Fantasy town',
    dimension: 'Fantasy Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/89',
      'https://rickandmortyapi.com/api/character/399',
      'https://rickandmortyapi.com/api/character/400',
    ],
    url: 'https://rickandmortyapi.com/api/location/14',
    created: '2017-11-18T11:31:15.248Z',
  },
  {
    id: 15,
    name: 'Bird World',
    type: 'Planet',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/15',
    created: '2017-11-18T11:32:26.752Z',
  },
  {
    id: 16,
    name: 'St. Gloopy Noops Hospital',
    type: 'Space station',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/105',
      'https://rickandmortyapi.com/api/character/263',
      'https://rickandmortyapi.com/api/character/321',
      'https://rickandmortyapi.com/api/character/383',
      'https://rickandmortyapi.com/api/character/384',
      'https://rickandmortyapi.com/api/character/454',
      'https://rickandmortyapi.com/api/character/455',
      'https://rickandmortyapi.com/api/character/456',
      'https://rickandmortyapi.com/api/character/460',
    ],
    url: 'https://rickandmortyapi.com/api/location/16',
    created: '2017-11-18T11:43:20.075Z',
  },
  {
    id: 17,
    name: 'Earth (5-126)',
    type: 'Planet',
    dimension: 'Dimension 5-126',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/17',
    created: '2017-11-18T11:41:08.486Z',
  },
  {
    id: 18,
    name: "Mr. Goldenfold's dream",
    type: 'Dream',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/63',
      'https://rickandmortyapi.com/api/character/80',
      'https://rickandmortyapi.com/api/character/221',
      'https://rickandmortyapi.com/api/character/246',
      'https://rickandmortyapi.com/api/character/304',
      'https://rickandmortyapi.com/api/character/305',
      'https://rickandmortyapi.com/api/character/306',
      'https://rickandmortyapi.com/api/character/396',
    ],
    url: 'https://rickandmortyapi.com/api/location/18',
    created: '2017-11-18T11:46:22.933Z',
  },
  {
    id: 19,
    name: 'Gromflom Prime',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/19',
    created: '2017-11-18T11:39:52.165Z',
  },
  {
    id: 20,
    name: 'Earth (Replacement Dimension)',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/9',
      'https://rickandmortyapi.com/api/character/11',
      'https://rickandmortyapi.com/api/character/13',
      'https://rickandmortyapi.com/api/character/16',
      'https://rickandmortyapi.com/api/character/31',
      'https://rickandmortyapi.com/api/character/32',
      'https://rickandmortyapi.com/api/character/50',
      'https://rickandmortyapi.com/api/character/58',
      'https://rickandmortyapi.com/api/character/59',
      'https://rickandmortyapi.com/api/character/64',
      'https://rickandmortyapi.com/api/character/66',
      'https://rickandmortyapi.com/api/character/76',
      'https://rickandmortyapi.com/api/character/88',
      'https://rickandmortyapi.com/api/character/103',
      'https://rickandmortyapi.com/api/character/107',
      'https://rickandmortyapi.com/api/character/109',
      'https://rickandmortyapi.com/api/character/113',
      'https://rickandmortyapi.com/api/character/115',
      'https://rickandmortyapi.com/api/character/124',
      'https://rickandmortyapi.com/api/character/128',
      'https://rickandmortyapi.com/api/character/137',
      'https://rickandmortyapi.com/api/character/138',
      'https://rickandmortyapi.com/api/character/141',
      'https://rickandmortyapi.com/api/character/147',
      'https://rickandmortyapi.com/api/character/149',
      'https://rickandmortyapi.com/api/character/151',
      'https://rickandmortyapi.com/api/character/154',
      'https://rickandmortyapi.com/api/character/166',
      'https://rickandmortyapi.com/api/character/167',
      'https://rickandmortyapi.com/api/character/170',
      'https://rickandmortyapi.com/api/character/171',
      'https://rickandmortyapi.com/api/character/172',
      'https://rickandmortyapi.com/api/character/180',
      'https://rickandmortyapi.com/api/character/181',
      'https://rickandmortyapi.com/api/character/182',
      'https://rickandmortyapi.com/api/character/185',
      'https://rickandmortyapi.com/api/character/189',
      'https://rickandmortyapi.com/api/character/190',
      'https://rickandmortyapi.com/api/character/210',
      'https://rickandmortyapi.com/api/character/217',
      'https://rickandmortyapi.com/api/character/218',
      'https://rickandmortyapi.com/api/character/219',
      'https://rickandmortyapi.com/api/character/227',
      'https://rickandmortyapi.com/api/character/230',
      'https://rickandmortyapi.com/api/character/233',
      'https://rickandmortyapi.com/api/character/234',
      'https://rickandmortyapi.com/api/character/236',
      'https://rickandmortyapi.com/api/character/237',
      'https://rickandmortyapi.com/api/character/240',
      'https://rickandmortyapi.com/api/character/241',
      'https://rickandmortyapi.com/api/character/243',
      'https://rickandmortyapi.com/api/character/244',
      'https://rickandmortyapi.com/api/character/245',
      'https://rickandmortyapi.com/api/character/248',
      'https://rickandmortyapi.com/api/character/251',
      'https://rickandmortyapi.com/api/character/255',
      'https://rickandmortyapi.com/api/character/259',
      'https://rickandmortyapi.com/api/character/262',
      'https://rickandmortyapi.com/api/character/265',
      'https://rickandmortyapi.com/api/character/272',
      'https://rickandmortyapi.com/api/character/276',
      'https://rickandmortyapi.com/api/character/280',
      'https://rickandmortyapi.com/api/character/292',
      'https://rickandmortyapi.com/api/character/293',
      'https://rickandmortyapi.com/api/character/324',
      'https://rickandmortyapi.com/api/character/326',
      'https://rickandmortyapi.com/api/character/327',
      'https://rickandmortyapi.com/api/character/332',
      'https://rickandmortyapi.com/api/character/335',
      'https://rickandmortyapi.com/api/character/341',
      'https://rickandmortyapi.com/api/character/346',
      'https://rickandmortyapi.com/api/character/347',
      'https://rickandmortyapi.com/api/character/352',
      'https://rickandmortyapi.com/api/character/353',
      'https://rickandmortyapi.com/api/character/354',
      'https://rickandmortyapi.com/api/character/357',
      'https://rickandmortyapi.com/api/character/360',
      'https://rickandmortyapi.com/api/character/361',
      'https://rickandmortyapi.com/api/character/363',
      'https://rickandmortyapi.com/api/character/365',
      'https://rickandmortyapi.com/api/character/374',
      'https://rickandmortyapi.com/api/character/377',
      'https://rickandmortyapi.com/api/character/390',
      'https://rickandmortyapi.com/api/character/391',
      'https://rickandmortyapi.com/api/character/401',
      'https://rickandmortyapi.com/api/character/402',
      'https://rickandmortyapi.com/api/character/405',
      'https://rickandmortyapi.com/api/character/423',
      'https://rickandmortyapi.com/api/character/435',
      'https://rickandmortyapi.com/api/character/437',
      'https://rickandmortyapi.com/api/character/438',
      'https://rickandmortyapi.com/api/character/439',
      'https://rickandmortyapi.com/api/character/440',
      'https://rickandmortyapi.com/api/character/452',
      'https://rickandmortyapi.com/api/character/453',
      'https://rickandmortyapi.com/api/character/467',
      'https://rickandmortyapi.com/api/character/468',
      'https://rickandmortyapi.com/api/character/469',
      'https://rickandmortyapi.com/api/character/471',
      'https://rickandmortyapi.com/api/character/492',
      'https://rickandmortyapi.com/api/character/493',
      'https://rickandmortyapi.com/api/character/497',
      'https://rickandmortyapi.com/api/character/509',
      'https://rickandmortyapi.com/api/character/510',
      'https://rickandmortyapi.com/api/character/511',
      'https://rickandmortyapi.com/api/character/512',
      'https://rickandmortyapi.com/api/character/513',
      'https://rickandmortyapi.com/api/character/514',
      'https://rickandmortyapi.com/api/character/516',
      'https://rickandmortyapi.com/api/character/517',
      'https://rickandmortyapi.com/api/character/523',
      'https://rickandmortyapi.com/api/character/524',
      'https://rickandmortyapi.com/api/character/526',
      'https://rickandmortyapi.com/api/character/534',
      'https://rickandmortyapi.com/api/character/535',
      'https://rickandmortyapi.com/api/character/536',
      'https://rickandmortyapi.com/api/character/537',
      'https://rickandmortyapi.com/api/character/538',
      'https://rickandmortyapi.com/api/character/539',
      'https://rickandmortyapi.com/api/character/540',
      'https://rickandmortyapi.com/api/character/541',
      'https://rickandmortyapi.com/api/character/561',
      'https://rickandmortyapi.com/api/character/562',
      'https://rickandmortyapi.com/api/character/564',
      'https://rickandmortyapi.com/api/character/570',
      'https://rickandmortyapi.com/api/character/575',
      'https://rickandmortyapi.com/api/character/584',
      'https://rickandmortyapi.com/api/character/585',
      'https://rickandmortyapi.com/api/character/586',
      'https://rickandmortyapi.com/api/character/588',
      'https://rickandmortyapi.com/api/character/590',
      'https://rickandmortyapi.com/api/character/591',
      'https://rickandmortyapi.com/api/character/592',
      'https://rickandmortyapi.com/api/character/667',
      'https://rickandmortyapi.com/api/character/672',
      'https://rickandmortyapi.com/api/character/680',
      'https://rickandmortyapi.com/api/character/684',
      'https://rickandmortyapi.com/api/character/686',
      'https://rickandmortyapi.com/api/character/687',
      'https://rickandmortyapi.com/api/character/688',
      'https://rickandmortyapi.com/api/character/689',
      'https://rickandmortyapi.com/api/character/690',
      'https://rickandmortyapi.com/api/character/691',
      'https://rickandmortyapi.com/api/character/692',
      'https://rickandmortyapi.com/api/character/693',
      'https://rickandmortyapi.com/api/character/694',
      'https://rickandmortyapi.com/api/character/695',
      'https://rickandmortyapi.com/api/character/696',
      'https://rickandmortyapi.com/api/character/697',
      'https://rickandmortyapi.com/api/character/698',
      'https://rickandmortyapi.com/api/character/699',
      'https://rickandmortyapi.com/api/character/700',
      'https://rickandmortyapi.com/api/character/701',
      'https://rickandmortyapi.com/api/character/702',
      'https://rickandmortyapi.com/api/character/703',
      'https://rickandmortyapi.com/api/character/704',
      'https://rickandmortyapi.com/api/character/705',
      'https://rickandmortyapi.com/api/character/706',
      'https://rickandmortyapi.com/api/character/707',
      'https://rickandmortyapi.com/api/character/708',
      'https://rickandmortyapi.com/api/character/710',
      'https://rickandmortyapi.com/api/character/712',
      'https://rickandmortyapi.com/api/character/713',
      'https://rickandmortyapi.com/api/character/714',
      'https://rickandmortyapi.com/api/character/715',
      'https://rickandmortyapi.com/api/character/716',
      'https://rickandmortyapi.com/api/character/717',
      'https://rickandmortyapi.com/api/character/719',
      'https://rickandmortyapi.com/api/character/720',
      'https://rickandmortyapi.com/api/character/721',
      'https://rickandmortyapi.com/api/character/722',
      'https://rickandmortyapi.com/api/character/723',
      'https://rickandmortyapi.com/api/character/724',
      'https://rickandmortyapi.com/api/character/725',
      'https://rickandmortyapi.com/api/character/726',
      'https://rickandmortyapi.com/api/character/727',
      'https://rickandmortyapi.com/api/character/728',
      'https://rickandmortyapi.com/api/character/729',
      'https://rickandmortyapi.com/api/character/730',
      'https://rickandmortyapi.com/api/character/732',
      'https://rickandmortyapi.com/api/character/733',
      'https://rickandmortyapi.com/api/character/734',
      'https://rickandmortyapi.com/api/character/735',
      'https://rickandmortyapi.com/api/character/737',
      'https://rickandmortyapi.com/api/character/738',
      'https://rickandmortyapi.com/api/character/739',
      'https://rickandmortyapi.com/api/character/740',
      'https://rickandmortyapi.com/api/character/741',
      'https://rickandmortyapi.com/api/character/742',
      'https://rickandmortyapi.com/api/character/753',
      'https://rickandmortyapi.com/api/character/754',
      'https://rickandmortyapi.com/api/character/755',
      'https://rickandmortyapi.com/api/character/756',
      'https://rickandmortyapi.com/api/character/757',
      'https://rickandmortyapi.com/api/character/758',
      'https://rickandmortyapi.com/api/character/759',
      'https://rickandmortyapi.com/api/character/760',
      'https://rickandmortyapi.com/api/character/761',
      'https://rickandmortyapi.com/api/character/762',
      'https://rickandmortyapi.com/api/character/763',
      'https://rickandmortyapi.com/api/character/764',
      'https://rickandmortyapi.com/api/character/765',
      'https://rickandmortyapi.com/api/character/766',
      'https://rickandmortyapi.com/api/character/767',
      'https://rickandmortyapi.com/api/character/768',
      'https://rickandmortyapi.com/api/character/769',
      'https://rickandmortyapi.com/api/character/770',
      'https://rickandmortyapi.com/api/character/771',
      'https://rickandmortyapi.com/api/character/772',
      'https://rickandmortyapi.com/api/character/773',
      'https://rickandmortyapi.com/api/character/774',
      'https://rickandmortyapi.com/api/character/775',
      'https://rickandmortyapi.com/api/character/776',
      'https://rickandmortyapi.com/api/character/777',
      'https://rickandmortyapi.com/api/character/778',
      'https://rickandmortyapi.com/api/character/781',
      'https://rickandmortyapi.com/api/character/786',
      'https://rickandmortyapi.com/api/character/788',
      'https://rickandmortyapi.com/api/character/789',
      'https://rickandmortyapi.com/api/character/790',
      'https://rickandmortyapi.com/api/character/791',
      'https://rickandmortyapi.com/api/character/203',
      'https://rickandmortyapi.com/api/character/794',
      'https://rickandmortyapi.com/api/character/800',
      'https://rickandmortyapi.com/api/character/813',
      'https://rickandmortyapi.com/api/character/821',
      'https://rickandmortyapi.com/api/character/826',
    ],
    url: 'https://rickandmortyapi.com/api/location/20',
    created: '2017-11-18T19:33:01.173Z',
  },
  {
    id: 21,
    name: 'Testicle Monster Dimension',
    type: 'Dimension',
    dimension: 'Testicle Monster Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/7',
      'https://rickandmortyapi.com/api/character/436',
    ],
    url: 'https://rickandmortyapi.com/api/location/21',
    created: '2017-11-18T19:41:01.605Z',
  },
  {
    id: 22,
    name: 'Signus 5 Expanse',
    type: 'unknown',
    dimension: 'Cromulon Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/24',
      'https://rickandmortyapi.com/api/character/309',
    ],
    url: 'https://rickandmortyapi.com/api/location/22',
    created: '2017-11-18T20:27:26.218Z',
  },
  {
    id: 23,
    name: 'Earth (C-500A)',
    type: 'Planet',
    dimension: 'Dimension C-500A',
    residents: [
      'https://rickandmortyapi.com/api/character/37',
      'https://rickandmortyapi.com/api/character/91',
      'https://rickandmortyapi.com/api/character/176',
      'https://rickandmortyapi.com/api/character/183',
      'https://rickandmortyapi.com/api/character/195',
    ],
    url: 'https://rickandmortyapi.com/api/location/23',
    created: '2017-11-18T20:58:15.178Z',
  },
  {
    id: 24,
    name: "Rick's Battery Microverse",
    type: 'Microverse',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/65',
      'https://rickandmortyapi.com/api/character/388',
    ],
    url: 'https://rickandmortyapi.com/api/location/24',
    created: '2017-11-30T11:02:41.722Z',
  },
  {
    id: 25,
    name: 'The Menagerie',
    type: 'Menagerie',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/67',
      'https://rickandmortyapi.com/api/character/490',
      'https://rickandmortyapi.com/api/character/491',
    ],
    url: 'https://rickandmortyapi.com/api/location/25',
    created: '2017-11-30T11:13:46.697Z',
  },
  {
    id: 26,
    name: 'Earth (K-83)',
    type: 'Planet',
    dimension: 'Dimension K-83',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/26',
    created: '2017-11-30T11:41:11.452Z',
  },
  {
    id: 27,
    name: 'Hideout Planet',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/79',
      'https://rickandmortyapi.com/api/character/84',
    ],
    url: 'https://rickandmortyapi.com/api/location/27',
    created: '2017-11-30T14:18:16.869Z',
  },
  {
    id: 28,
    name: "Unity's Planet",
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/90',
      'https://rickandmortyapi.com/api/character/188',
      'https://rickandmortyapi.com/api/character/301',
      'https://rickandmortyapi.com/api/character/336',
      'https://rickandmortyapi.com/api/character/355',
      'https://rickandmortyapi.com/api/character/372',
    ],
    url: 'https://rickandmortyapi.com/api/location/28',
    created: '2017-11-30T14:28:54.591Z',
  },
  {
    id: 29,
    name: 'Dorian 5',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/93',
      'https://rickandmortyapi.com/api/character/104',
      'https://rickandmortyapi.com/api/character/198',
    ],
    url: 'https://rickandmortyapi.com/api/location/29',
    created: '2017-12-01T11:36:16.463Z',
  },
  {
    id: 30,
    name: 'Earth (Unknown dimension)',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/822',
      'https://rickandmortyapi.com/api/character/823',
      'https://rickandmortyapi.com/api/character/824',
      'https://rickandmortyapi.com/api/character/825',
    ],
    url: 'https://rickandmortyapi.com/api/location/30',
    created: '2017-12-01T11:49:43.923Z',
  },
  {
    id: 31,
    name: 'Earth (J19ζ7)',
    type: 'Planet',
    dimension: 'Dimension J19ζ7',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/31',
    created: '2017-12-01T12:29:27.976Z',
  },
  {
    id: 32,
    name: 'Roy: A Life Well Lived',
    type: 'Game',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/106',
      'https://rickandmortyapi.com/api/character/393',
      'https://rickandmortyapi.com/api/character/449',
      'https://rickandmortyapi.com/api/character/450',
      'https://rickandmortyapi.com/api/character/451',
    ],
    url: 'https://rickandmortyapi.com/api/location/32',
    created: '2017-12-26T12:46:48.798Z',
  },
  {
    id: 33,
    name: 'Eric Stoltz Mask Earth',
    type: 'Planet',
    dimension: 'Eric Stoltz Mask Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/33',
    created: '2017-12-26T13:43:29.291Z',
  },
  {
    id: 34,
    name: "Earth (Evil Rick's Target Dimension)",
    type: 'Planet',
    dimension: "Evil Rick's Target Dimension",
    residents: [
      'https://rickandmortyapi.com/api/character/39',
      'https://rickandmortyapi.com/api/character/177',
      'https://rickandmortyapi.com/api/character/232',
      'https://rickandmortyapi.com/api/character/290',
      'https://rickandmortyapi.com/api/character/339',
    ],
    url: 'https://rickandmortyapi.com/api/location/34',
    created: '2017-12-26T15:35:20.499Z',
  },
  {
    id: 35,
    name: 'Planet Squanch',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/47',
      'https://rickandmortyapi.com/api/character/75',
      'https://rickandmortyapi.com/api/character/102',
      'https://rickandmortyapi.com/api/character/194',
      'https://rickandmortyapi.com/api/character/199',
      'https://rickandmortyapi.com/api/character/256',
      'https://rickandmortyapi.com/api/character/261',
      'https://rickandmortyapi.com/api/character/308',
      'https://rickandmortyapi.com/api/character/311',
      'https://rickandmortyapi.com/api/character/331',
      'https://rickandmortyapi.com/api/character/379',
    ],
    url: 'https://rickandmortyapi.com/api/location/35',
    created: '2017-12-26T17:51:53.018Z',
  },
  {
    id: 36,
    name: 'Glaagablaaga',
    type: 'Planet',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/36',
    created: '2017-12-26T20:30:45.939Z',
  },
  {
    id: 37,
    name: 'Resort Planet',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/142',
      'https://rickandmortyapi.com/api/character/296',
      'https://rickandmortyapi.com/api/character/297',
      'https://rickandmortyapi.com/api/character/319',
      'https://rickandmortyapi.com/api/character/369',
    ],
    url: 'https://rickandmortyapi.com/api/location/37',
    created: '2017-12-27T20:02:59.005Z',
  },
  {
    id: 38,
    name: 'Interdimensional Customs',
    type: 'Customs',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/144',
      'https://rickandmortyapi.com/api/character/158',
    ],
    url: 'https://rickandmortyapi.com/api/location/38',
    created: '2017-12-29T10:37:48.281Z',
  },
  {
    id: 39,
    name: 'Galactic Federation Prison',
    type: 'Space station',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/150'],
    url: 'https://rickandmortyapi.com/api/location/39',
    created: '2017-12-29T12:02:33.513Z',
  },
  {
    id: 40,
    name: 'Gazorpazorp',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/168',
      'https://rickandmortyapi.com/api/character/211',
      'https://rickandmortyapi.com/api/character/376',
    ],
    url: 'https://rickandmortyapi.com/api/location/40',
    created: '2017-12-29T12:31:50.313Z',
  },
  {
    id: 41,
    name: 'Hamster in Butt World',
    type: 'Planet',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/153'],
    url: 'https://rickandmortyapi.com/api/location/41',
    created: '2017-12-29T15:27:54.209Z',
  },
  {
    id: 42,
    name: 'Earth (Giant Telepathic Spiders Dimension)',
    type: 'Planet',
    dimension: 'Giant Telepathic Spiders Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/159',
      'https://rickandmortyapi.com/api/character/160',
    ],
    url: 'https://rickandmortyapi.com/api/location/42',
    created: '2017-12-29T16:03:28.720Z',
  },
  {
    id: 43,
    name: 'Alphabetrium',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/161',
      'https://rickandmortyapi.com/api/character/162',
      'https://rickandmortyapi.com/api/character/212',
      'https://rickandmortyapi.com/api/character/213',
      'https://rickandmortyapi.com/api/character/253',
    ],
    url: 'https://rickandmortyapi.com/api/location/43',
    created: '2017-12-29T16:08:47.694Z',
  },
  {
    id: 44,
    name: 'Jerryboree',
    type: 'Daycare',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/174',
      'https://rickandmortyapi.com/api/character/257',
      'https://rickandmortyapi.com/api/character/441',
      'https://rickandmortyapi.com/api/character/442',
      'https://rickandmortyapi.com/api/character/443',
      'https://rickandmortyapi.com/api/character/444',
      'https://rickandmortyapi.com/api/character/445',
      'https://rickandmortyapi.com/api/character/446',
    ],
    url: 'https://rickandmortyapi.com/api/location/44',
    created: '2017-12-29T17:50:19.947Z',
  },
  {
    id: 45,
    name: 'Krootabulon',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/45',
    created: '2017-12-29T19:26:06.827Z',
  },
  {
    id: 46,
    name: "Zigerion's Base",
    type: 'Space station',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/87',
      'https://rickandmortyapi.com/api/character/191',
      'https://rickandmortyapi.com/api/character/270',
      'https://rickandmortyapi.com/api/character/337',
    ],
    url: 'https://rickandmortyapi.com/api/location/46',
    created: '2017-12-29T19:40:07.748Z',
  },
  {
    id: 47,
    name: 'Pluto',
    type: 'Dwarf planet (Celestial Dwarf)',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/192',
      'https://rickandmortyapi.com/api/character/307',
      'https://rickandmortyapi.com/api/character/419',
      'https://rickandmortyapi.com/api/character/420',
      'https://rickandmortyapi.com/api/character/421',
      'https://rickandmortyapi.com/api/character/422',
    ],
    url: 'https://rickandmortyapi.com/api/location/47',
    created: '2017-12-29T19:49:29.228Z',
  },
  {
    id: 48,
    name: 'Fantasy World',
    type: 'Planet',
    dimension: 'Fantasy Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/41',
      'https://rickandmortyapi.com/api/character/193',
      'https://rickandmortyapi.com/api/character/238',
      'https://rickandmortyapi.com/api/character/333',
    ],
    url: 'https://rickandmortyapi.com/api/location/48',
    created: '2017-12-29T19:55:54.672Z',
  },
  {
    id: 49,
    name: "Zeep Xanflorp's Miniverse",
    type: 'Miniverse',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/348'],
    url: 'https://rickandmortyapi.com/api/location/49',
    created: '2017-12-29T19:58:44.675Z',
  },
  {
    id: 50,
    name: "Kyle's Teenyverse",
    type: 'Teenyverse',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/197',
      'https://rickandmortyapi.com/api/character/364',
    ],
    url: 'https://rickandmortyapi.com/api/location/50',
    created: '2017-12-30T12:36:19.730Z',
  },
  {
    id: 51,
    name: "Larva Alien's Planet",
    type: 'Planet',
    dimension: 'Unknown dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/51',
    created: '2017-12-30T12:48:19.312Z',
  },
  {
    id: 52,
    name: 'Earth (K-22)',
    type: 'Planet',
    dimension: 'Dimension K-22',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/52',
    created: '2017-12-30T16:33:49.507Z',
  },
  {
    id: 53,
    name: 'Mr. Meeseeks Box',
    type: 'Box',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/53',
    created: '2017-12-30T17:52:12.217Z',
  },
  {
    id: 54,
    name: "Vindicator's Base",
    type: 'Spacecraft',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/252'],
    url: 'https://rickandmortyapi.com/api/location/54',
    created: '2017-12-31T12:57:37.824Z',
  },
  {
    id: 55,
    name: 'Pawn Shop Planet',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/258'],
    url: 'https://rickandmortyapi.com/api/location/55',
    created: '2017-12-31T13:30:33.579Z',
  },
  {
    id: 56,
    name: 'Mega Gargantuan Kingdom',
    type: 'Microverse',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/269'],
    url: 'https://rickandmortyapi.com/api/location/56',
    created: '2017-12-31T14:01:44.921Z',
  },
  {
    id: 57,
    name: 'Gear World',
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/282',
      'https://rickandmortyapi.com/api/character/447',
      'https://rickandmortyapi.com/api/character/448',
    ],
    url: 'https://rickandmortyapi.com/api/location/57',
    created: '2017-12-31T19:21:17.276Z',
  },
  {
    id: 58,
    name: 'Earth (D-99)',
    type: 'Planet',
    dimension: 'Dimension D-99',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/58',
    created: '2017-12-31T19:49:55.109Z',
  },
  {
    id: 59,
    name: 'Earth (D716)',
    type: 'Planet',
    dimension: 'Dimension D716',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/59',
    created: '2017-12-31T19:51:33.170Z',
  },
  {
    id: 60,
    name: 'Earth (D716-B)',
    type: 'Planet',
    dimension: 'Dimension D716-B',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/60',
    created: '2017-12-31T19:55:25.026Z',
  },
  {
    id: 61,
    name: 'Earth (D716-C)',
    type: 'Planet',
    dimension: 'Dimension D716-C',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/61',
    created: '2017-12-31T19:57:36.468Z',
  },
  {
    id: 62,
    name: 'Earth (J-22)',
    type: 'Planet',
    dimension: 'Dimension J-22',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/62',
    created: '2017-12-31T20:16:52.263Z',
  },
  {
    id: 63,
    name: 'Froopyland',
    type: 'Artificially generated world',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/350'],
    url: 'https://rickandmortyapi.com/api/location/63',
    created: '2018-01-10T17:55:14.227Z',
  },
  {
    id: 64,
    name: 'Detoxifier',
    type: 'Machine',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/64',
    created: '2018-01-10T18:20:41.627Z',
  },
  {
    id: 65,
    name: 'Trunk World',
    type: 'Planet',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/65',
    created: '2018-01-10T19:03:13.484Z',
  },
  {
    id: 66,
    name: 'Plopstar',
    type: 'Planet',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/371'],
    url: 'https://rickandmortyapi.com/api/location/66',
    created: '2018-01-10T19:56:57.717Z',
  },
  {
    id: 67,
    name: 'Blips and Chitz',
    type: 'Arcade',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/67',
    created: '2018-01-21T19:01:19.496Z',
  },
  {
    id: 68,
    name: 'Girvonesk',
    type: 'unknown',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/68',
    created: '2018-04-15T16:39:38.598Z',
  },
  {
    id: 69,
    name: 'Earth (C-35)',
    type: 'Planet',
    dimension: 'Dimension C-35',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/69',
    created: '2018-04-15T16:55:56.212Z',
  },
  {
    id: 70,
    name: "Snuffles' Dream",
    type: 'Dream',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/397',
      'https://rickandmortyapi.com/api/character/398',
    ],
    url: 'https://rickandmortyapi.com/api/location/70',
    created: '2018-04-15T17:13:54.071Z',
  },
  {
    id: 71,
    name: 'Earth (Pizza Dimension)',
    type: 'Planet',
    dimension: 'Pizza Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/424',
      'https://rickandmortyapi.com/api/character/425',
    ],
    url: 'https://rickandmortyapi.com/api/location/71',
    created: '2018-04-15T17:55:04.478Z',
  },
  {
    id: 72,
    name: 'Earth (Phone Dimension)',
    type: 'Planet',
    dimension: 'Phone Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/404',
      'https://rickandmortyapi.com/api/character/427',
      'https://rickandmortyapi.com/api/character/428',
    ],
    url: 'https://rickandmortyapi.com/api/location/72',
    created: '2018-04-15T17:56:09.117Z',
  },
  {
    id: 73,
    name: 'Greasy Grandma World',
    type: 'Planet',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/426'],
    url: 'https://rickandmortyapi.com/api/location/73',
    created: '2018-04-16T21:50:20.144Z',
  },
  {
    id: 74,
    name: 'Earth (Chair Dimension)',
    type: 'Planet',
    dimension: 'Chair Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/429',
      'https://rickandmortyapi.com/api/character/430',
      'https://rickandmortyapi.com/api/character/431',
      'https://rickandmortyapi.com/api/character/432',
    ],
    url: 'https://rickandmortyapi.com/api/location/74',
    created: '2018-04-16T21:58:24.292Z',
  },
  {
    id: 75,
    name: 'Árboles Mentirosos',
    type: 'Planet',
    dimension: 'unknown',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/75',
    created: '2018-05-01T15:27:20.251Z',
  },
  {
    id: 76,
    name: 'Alien Day Spa',
    type: 'Spa',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/470'],
    url: 'https://rickandmortyapi.com/api/location/76',
    created: '2018-05-22T20:49:01.820Z',
  },
  {
    id: 77,
    name: 'Earth (Fascist Dimension)',
    type: 'Planet',
    dimension: 'Fascist Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/242',
      'https://rickandmortyapi.com/api/character/498',
      'https://rickandmortyapi.com/api/character/499',
      'https://rickandmortyapi.com/api/character/500',
      'https://rickandmortyapi.com/api/character/501',
      'https://rickandmortyapi.com/api/character/502',
    ],
    url: 'https://rickandmortyapi.com/api/location/77',
    created: '2020-05-02T09:39:49.158Z',
  },
  {
    id: 78,
    name: 'Snake Planet',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/313',
      'https://rickandmortyapi.com/api/character/571',
      'https://rickandmortyapi.com/api/character/572',
      'https://rickandmortyapi.com/api/character/573',
      'https://rickandmortyapi.com/api/character/574',
      'https://rickandmortyapi.com/api/character/576',
      'https://rickandmortyapi.com/api/character/577',
      'https://rickandmortyapi.com/api/character/578',
      'https://rickandmortyapi.com/api/character/579',
      'https://rickandmortyapi.com/api/character/580',
      'https://rickandmortyapi.com/api/character/581',
      'https://rickandmortyapi.com/api/character/582',
      'https://rickandmortyapi.com/api/character/583',
      'https://rickandmortyapi.com/api/character/587',
      'https://rickandmortyapi.com/api/character/589',
    ],
    url: 'https://rickandmortyapi.com/api/location/78',
    created: '2020-05-02T09:47:39.754Z',
  },
  {
    id: 79,
    name: 'Forbodulon Prime',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/494',
      'https://rickandmortyapi.com/api/character/495',
      'https://rickandmortyapi.com/api/character/496',
    ],
    url: 'https://rickandmortyapi.com/api/location/79',
    created: '2020-05-02T10:04:05.509Z',
  },
  {
    id: 80,
    name: 'Earth (Fascist Shrimp Dimension)',
    type: 'Planet',
    dimension: 'Fascist Shrimp Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/503',
      'https://rickandmortyapi.com/api/character/504',
      'https://rickandmortyapi.com/api/character/505',
      'https://rickandmortyapi.com/api/character/506',
    ],
    url: 'https://rickandmortyapi.com/api/location/80',
    created: '2020-05-02T11:52:35.156Z',
  },
  {
    id: 81,
    name: 'Earth (Fascist Teddy Bear Dimension)',
    type: 'Planet',
    dimension: 'Fascist Teddy Bear Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/507',
      'https://rickandmortyapi.com/api/character/508',
    ],
    url: 'https://rickandmortyapi.com/api/location/81',
    created: '2020-05-02T12:16:18.224Z',
  },
  {
    id: 82,
    name: 'Earth (Wasp Dimension)',
    type: 'Planet',
    dimension: 'Wasp Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/515',
      'https://rickandmortyapi.com/api/character/518',
      'https://rickandmortyapi.com/api/character/519',
      'https://rickandmortyapi.com/api/character/520',
      'https://rickandmortyapi.com/api/character/521',
      'https://rickandmortyapi.com/api/character/522',
    ],
    url: 'https://rickandmortyapi.com/api/location/82',
    created: '2020-05-02T12:34:19.656Z',
  },
  {
    id: 83,
    name: 'Monogatron Mothership',
    type: 'Space station',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/525',
      'https://rickandmortyapi.com/api/character/527',
      'https://rickandmortyapi.com/api/character/528',
      'https://rickandmortyapi.com/api/character/533',
    ],
    url: 'https://rickandmortyapi.com/api/location/83',
    created: '2020-05-02T13:10:42.299Z',
  },
  {
    id: 84,
    name: 'Gorgon Quadrant',
    type: 'Quadrant',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/543'],
    url: 'https://rickandmortyapi.com/api/location/84',
    created: '2020-05-02T13:21:49.663Z',
  },
  {
    id: 85,
    name: 'Midland Quasar',
    type: 'Quasar',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/529',
      'https://rickandmortyapi.com/api/character/530',
    ],
    url: 'https://rickandmortyapi.com/api/location/85',
    created: '2020-05-02T13:30:41.732Z',
  },
  {
    id: 86,
    name: 'Mount Space Everest',
    type: 'Mount',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/531'],
    url: 'https://rickandmortyapi.com/api/location/86',
    created: '2020-05-02T13:34:45.332Z',
  },
  {
    id: 87,
    name: 'Globaflyn',
    type: 'Liquid',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/532',
      'https://rickandmortyapi.com/api/character/542',
    ],
    url: 'https://rickandmortyapi.com/api/location/87',
    created: '2020-05-02T13:44:54.688Z',
  },
  {
    id: 88,
    name: 'Heist-Con',
    type: 'Convention',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/544',
      'https://rickandmortyapi.com/api/character/545',
      'https://rickandmortyapi.com/api/character/546',
      'https://rickandmortyapi.com/api/character/547',
      'https://rickandmortyapi.com/api/character/548',
      'https://rickandmortyapi.com/api/character/549',
      'https://rickandmortyapi.com/api/character/550',
      'https://rickandmortyapi.com/api/character/551',
      'https://rickandmortyapi.com/api/character/552',
      'https://rickandmortyapi.com/api/character/553',
    ],
    url: 'https://rickandmortyapi.com/api/location/88',
    created: '2020-05-07T09:07:41.816Z',
  },
  {
    id: 89,
    name: 'Heistotron Base',
    type: 'Space station',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/554',
      'https://rickandmortyapi.com/api/character/555',
      'https://rickandmortyapi.com/api/character/556',
      'https://rickandmortyapi.com/api/character/557',
      'https://rickandmortyapi.com/api/character/558',
    ],
    url: 'https://rickandmortyapi.com/api/location/89',
    created: '2020-05-07T10:11:40.632Z',
  },
  {
    id: 90,
    name: 'Mount Olympus',
    type: 'Mount',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/90',
    created: '2020-05-07T10:19:34.206Z',
  },
  {
    id: 91,
    name: 'Plitzville Montana',
    type: 'Woods',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/91',
    created: '2020-05-07T10:23:07.595Z',
  },
  {
    id: 92,
    name: 'Earth (Tusk Dimension)',
    type: 'Planet',
    dimension: 'Tusk Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/92',
    created: '2020-05-07T10:25:11.950Z',
  },
  {
    id: 93,
    name: 'Gramuflack',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/559',
      'https://rickandmortyapi.com/api/character/560',
    ],
    url: 'https://rickandmortyapi.com/api/location/93',
    created: '2020-05-07T10:26:35.591Z',
  },
  {
    id: 94,
    name: 'Draygon',
    type: 'Planet',
    dimension: 'Magic Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/563',
      'https://rickandmortyapi.com/api/character/565',
      'https://rickandmortyapi.com/api/character/566',
      'https://rickandmortyapi.com/api/character/567',
      'https://rickandmortyapi.com/api/character/568',
      'https://rickandmortyapi.com/api/character/569',
    ],
    url: 'https://rickandmortyapi.com/api/location/94',
    created: '2020-05-07T11:30:49.963Z',
  },
  {
    id: 95,
    name: 'New Improved Galactic Federation Quarters',
    type: 'Space station',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/95',
    created: '2020-08-05T12:42:58.048Z',
  },
  {
    id: 96,
    name: 'Story Train',
    type: 'Diegesis',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/597',
      'https://rickandmortyapi.com/api/character/598',
      'https://rickandmortyapi.com/api/character/599',
      'https://rickandmortyapi.com/api/character/600',
      'https://rickandmortyapi.com/api/character/601',
      'https://rickandmortyapi.com/api/character/606',
      'https://rickandmortyapi.com/api/character/607',
      'https://rickandmortyapi.com/api/character/611',
      'https://rickandmortyapi.com/api/character/612',
      'https://rickandmortyapi.com/api/character/615',
      'https://rickandmortyapi.com/api/character/616',
      'https://rickandmortyapi.com/api/character/617',
      'https://rickandmortyapi.com/api/character/618',
      'https://rickandmortyapi.com/api/character/619',
      'https://rickandmortyapi.com/api/character/620',
      'https://rickandmortyapi.com/api/character/622',
      'https://rickandmortyapi.com/api/character/623',
      'https://rickandmortyapi.com/api/character/624',
      'https://rickandmortyapi.com/api/character/626',
      'https://rickandmortyapi.com/api/character/627',
      'https://rickandmortyapi.com/api/character/630',
      'https://rickandmortyapi.com/api/character/631',
      'https://rickandmortyapi.com/api/character/632',
      'https://rickandmortyapi.com/api/character/633',
      'https://rickandmortyapi.com/api/character/634',
      'https://rickandmortyapi.com/api/character/637',
      'https://rickandmortyapi.com/api/character/638',
    ],
    url: 'https://rickandmortyapi.com/api/location/96',
    created: '2020-08-06T09:47:28.216Z',
  },
  {
    id: 97,
    name: 'Non-Diegetic Alternative Reality',
    type: 'Non-Diegetic Alternative Reality',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/593'],
    url: 'https://rickandmortyapi.com/api/location/97',
    created: '2020-08-06T09:50:13.771Z',
  },
  {
    id: 98,
    name: 'Tickets Please Guy Nightmare',
    type: 'Nightmare',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/594',
      'https://rickandmortyapi.com/api/character/595',
      'https://rickandmortyapi.com/api/character/596',
      'https://rickandmortyapi.com/api/character/605',
      'https://rickandmortyapi.com/api/character/609',
      'https://rickandmortyapi.com/api/character/610',
      'https://rickandmortyapi.com/api/character/639',
    ],
    url: 'https://rickandmortyapi.com/api/location/98',
    created: '2020-08-06T09:52:43.580Z',
  },
  {
    id: 99,
    name: 'Morty’s Story',
    type: 'Diegesis',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/602',
      'https://rickandmortyapi.com/api/character/604',
      'https://rickandmortyapi.com/api/character/613',
      'https://rickandmortyapi.com/api/character/628',
      'https://rickandmortyapi.com/api/character/629',
      'https://rickandmortyapi.com/api/character/621',
    ],
    url: 'https://rickandmortyapi.com/api/location/99',
    created: '2020-08-06T11:42:46.054Z',
  },
  {
    id: 100,
    name: 'Ricks’s Story',
    type: 'Diegesis',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/603',
      'https://rickandmortyapi.com/api/character/614',
      'https://rickandmortyapi.com/api/character/625',
      'https://rickandmortyapi.com/api/character/635',
      'https://rickandmortyapi.com/api/character/636',
      'https://rickandmortyapi.com/api/character/608',
    ],
    url: 'https://rickandmortyapi.com/api/location/100',
    created: '2020-08-06T11:45:08.782Z',
  },
  {
    id: 101,
    name: 'Glorzo Asteroid',
    type: 'Asteroid',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/640',
      'https://rickandmortyapi.com/api/character/641',
      'https://rickandmortyapi.com/api/character/642',
      'https://rickandmortyapi.com/api/character/643',
      'https://rickandmortyapi.com/api/character/644',
      'https://rickandmortyapi.com/api/character/645',
      'https://rickandmortyapi.com/api/character/646',
      'https://rickandmortyapi.com/api/character/647',
    ],
    url: 'https://rickandmortyapi.com/api/location/101',
    created: '2020-08-07T11:28:46.897Z',
  },
  {
    id: 102,
    name: 'Alien Acid Plant',
    type: 'Acid Plant',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/648',
      'https://rickandmortyapi.com/api/character/649',
      'https://rickandmortyapi.com/api/character/650',
      'https://rickandmortyapi.com/api/character/651',
    ],
    url: 'https://rickandmortyapi.com/api/location/102',
    created: '2020-08-13T10:08:12.986Z',
  },
  {
    id: 103,
    name: 'Merged Universe',
    type: 'Dimension',
    dimension: 'Merged Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/652',
      'https://rickandmortyapi.com/api/character/656',
      'https://rickandmortyapi.com/api/character/657',
      'https://rickandmortyapi.com/api/character/658',
      'https://rickandmortyapi.com/api/character/661',
      'https://rickandmortyapi.com/api/character/655',
    ],
    url: 'https://rickandmortyapi.com/api/location/103',
    created: '2020-08-13T10:16:18.946Z',
  },
  {
    id: 104,
    name: 'Near-Duplicate Reality',
    type: 'Reality',
    dimension: 'Unknown dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/653',
      'https://rickandmortyapi.com/api/character/654',
      'https://rickandmortyapi.com/api/character/659',
      'https://rickandmortyapi.com/api/character/660',
    ],
    url: 'https://rickandmortyapi.com/api/location/104',
    created: '2020-08-13T11:15:54.414Z',
  },
  {
    id: 105,
    name: 'NX-5 Planet Remover',
    type: 'Death Star',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/344',
      'https://rickandmortyapi.com/api/character/670',
      'https://rickandmortyapi.com/api/character/671',
    ],
    url: 'https://rickandmortyapi.com/api/location/105',
    created: '2020-08-13T11:35:53.644Z',
  },
  {
    id: 106,
    name: 'Gaia',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/662',
      'https://rickandmortyapi.com/api/character/663',
      'https://rickandmortyapi.com/api/character/664',
      'https://rickandmortyapi.com/api/character/665',
      'https://rickandmortyapi.com/api/character/666',
    ],
    url: 'https://rickandmortyapi.com/api/location/106',
    created: '2020-08-13T12:00:29.825Z',
  },
  {
    id: 107,
    name: "Defiance's Ship",
    type: 'Spacecraft',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/668'],
    url: 'https://rickandmortyapi.com/api/location/107',
    created: '2020-08-13T13:05:33.161Z',
  },
  {
    id: 108,
    name: "Defiance's Base",
    type: 'Base',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/669'],
    url: 'https://rickandmortyapi.com/api/location/108',
    created: '2020-08-13T13:07:01.192Z',
  },
  {
    id: 109,
    name: 'The Ocean',
    type: 'Liquid',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/109',
    created: '2021-10-16T11:53:50.571Z',
  },
  {
    id: 110,
    name: 'Narnia Dimension',
    type: 'Dimension',
    dimension: 'Fantasy Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/673',
      'https://rickandmortyapi.com/api/character/674',
      'https://rickandmortyapi.com/api/character/675',
      'https://rickandmortyapi.com/api/character/676',
      'https://rickandmortyapi.com/api/character/677',
      'https://rickandmortyapi.com/api/character/678',
      'https://rickandmortyapi.com/api/character/679',
      'https://rickandmortyapi.com/api/character/681',
      'https://rickandmortyapi.com/api/character/682',
      'https://rickandmortyapi.com/api/character/683',
      'https://rickandmortyapi.com/api/character/685',
    ],
    url: 'https://rickandmortyapi.com/api/location/110',
    created: '2021-10-16T11:59:26.649Z',
  },
  {
    id: 111,
    name: 'Elemental Rings',
    type: 'Elemental Rings',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/111',
    created: '2021-10-17T09:49:31.948Z',
  },
  {
    id: 112,
    name: 'Morglutz',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/799'],
    url: 'https://rickandmortyapi.com/api/location/112',
    created: '2021-10-17T09:51:34.413Z',
  },
  {
    id: 113,
    name: 'Ferkus 9',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/718',
      'https://rickandmortyapi.com/api/character/798',
    ],
    url: 'https://rickandmortyapi.com/api/location/113',
    created: '2021-10-17T09:52:23.219Z',
  },
  {
    id: 114,
    name: 'Morty',
    type: 'Human',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/114',
    created: '2021-10-17T10:08:24.040Z',
  },
  {
    id: 115,
    name: 'Space',
    type: 'Space',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/731',
      'https://rickandmortyapi.com/api/character/736',
    ],
    url: 'https://rickandmortyapi.com/api/location/115',
    created: '2021-10-17T11:55:43.920Z',
  },
  {
    id: 116,
    name: 'Hell',
    type: 'Hell',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/744',
      'https://rickandmortyapi.com/api/character/745',
      'https://rickandmortyapi.com/api/character/746',
      'https://rickandmortyapi.com/api/character/747',
      'https://rickandmortyapi.com/api/character/748',
      'https://rickandmortyapi.com/api/character/749',
      'https://rickandmortyapi.com/api/character/750',
    ],
    url: 'https://rickandmortyapi.com/api/location/116',
    created: '2021-10-17T12:31:59.067Z',
  },
  {
    id: 117,
    name: 'Z. Q. P. D.',
    type: 'Police Department',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/743'],
    url: 'https://rickandmortyapi.com/api/location/117',
    created: '2021-10-17T13:45:50.845Z',
  },
  {
    id: 118,
    name: 'Space Tahoe',
    type: '',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/751',
      'https://rickandmortyapi.com/api/character/752',
    ],
    url: 'https://rickandmortyapi.com/api/location/118',
    created: '2021-10-17T14:03:13.221Z',
  },
  {
    id: 119,
    name: 'France',
    type: 'Country',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/119',
    created: '2021-10-17T14:59:13.494Z',
  },
  {
    id: 120,
    name: "Birdperson's Consciousness",
    type: 'Consciousness',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/780',
      'https://rickandmortyapi.com/api/character/782',
      'https://rickandmortyapi.com/api/character/783',
      'https://rickandmortyapi.com/api/character/784',
      'https://rickandmortyapi.com/api/character/785',
    ],
    url: 'https://rickandmortyapi.com/api/location/120',
    created: '2021-10-25T09:06:22.109Z',
  },
  {
    id: 121,
    name: "Rick's Consciousness",
    type: 'Consciousness',
    dimension: 'Replacement Dimension',
    residents: [],
    url: 'https://rickandmortyapi.com/api/location/121',
    created: '2021-10-25T09:12:23.715Z',
  },
  {
    id: 122,
    name: 'Avian Planet',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/792',
      'https://rickandmortyapi.com/api/character/793',
    ],
    url: 'https://rickandmortyapi.com/api/location/122',
    created: '2021-10-26T12:19:52.957Z',
  },
  {
    id: 123,
    name: 'Normal Size Bug Dimension',
    type: 'Dimension',
    dimension: '',
    residents: [
      'https://rickandmortyapi.com/api/character/795',
      'https://rickandmortyapi.com/api/character/796',
    ],
    url: 'https://rickandmortyapi.com/api/location/123',
    created: '2021-11-02T13:03:21.307Z',
  },
  {
    id: 124,
    name: 'Slartivart',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: ['https://rickandmortyapi.com/api/character/797'],
    url: 'https://rickandmortyapi.com/api/location/124',
    created: '2021-11-02T13:07:27.619Z',
  },
  {
    id: 125,
    name: 'Rick and Two Crows Planet',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/809',
      'https://rickandmortyapi.com/api/character/808',
      'https://rickandmortyapi.com/api/character/787',
    ],
    url: 'https://rickandmortyapi.com/api/location/125',
    created: '2021-11-02T13:50:55.588Z',
  },
  {
    id: 126,
    name: "Rick's Memories",
    type: 'Memory',
    dimension: '',
    residents: [
      'https://rickandmortyapi.com/api/character/815',
      'https://rickandmortyapi.com/api/character/814',
      'https://rickandmortyapi.com/api/character/807',
      'https://rickandmortyapi.com/api/character/94',
      'https://rickandmortyapi.com/api/character/779',
      'https://rickandmortyapi.com/api/character/816',
      'https://rickandmortyapi.com/api/character/817',
      'https://rickandmortyapi.com/api/character/274',
      'https://rickandmortyapi.com/api/character/389',
      'https://rickandmortyapi.com/api/character/215',
      'https://rickandmortyapi.com/api/character/294',
    ],
    url: 'https://rickandmortyapi.com/api/location/126',
    created: '2021-11-02T15:18:57.987Z',
  },
]

export default locations
